#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

import agent

request = json.load(sys.stdin)
host = request["host"]

# The Let's Encrypt flag is stored by Traefik in the route
agent.set_env("IDP_HOSTNAME", host)

# Publish the identity provider for service discovery. Applications find
# the issuer of a user domain at https://{host}/realms/{domain}
agent_id = os.environ["AGENT_ID"]
srv_key = f"{agent_id}/srv/http/idp"
rdb = agent.redis_connect(privileged=True)
rdb.hset(srv_key, mapping={"host": host})
rdb.publish(f"{agent_id}/event/service-idp-changed", json.dumps({
    "key": srv_key,
    "module_id": os.environ["MODULE_ID"],
    "module_uuid": os.environ["MODULE_UUID"],
}))
