#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)

# The Let's Encrypt flag is stored by Traefik in the route
agent.set_env("IDP_HOSTNAME", request["host"])
