#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

systemctl --user enable idp.service
# List every unit: restarting the pod alone does not restart its containers
systemctl --user restart idp.service postgres.service keycloak.service
