#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import secrets

import agent

if os.path.exists("passwords.env"):
    exit(0)

db_password = secrets.token_urlsafe(32)
os.umask(0o077)
with agent.safe_open("passwords.env") as fp:
    print(f"POSTGRES_PASSWORD={db_password}", file=fp)
    print(f"KC_DB_PASSWORD={db_password}", file=fp)
